# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LenditUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_user', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('type', models.CharField(choices=[('r', 'r'), ('a', 'a'), ('d', 'd')], max_length=1)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.LenditUser')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.IntegerField()),
                ('book', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.LenditUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
                ('condition', models.CharField(max_length=100)),
                ('lending_time', models.IntegerField()),
                ('image_url', models.URLField()),
                ('status', models.CharField(choices=[('lent', 'lent'), ('unlent', 'unlent')], max_length=10)),
                ('orig_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.LenditUser')),
            ],
        ),
    ]
