# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_lendituser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.UserBook')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender', to='website.LenditUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='website.LenditUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='requestsent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='book_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.UserBook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='other_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_user', to='website.LenditUser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_user', to='website.LenditUser'),
        ),
        migrations.DeleteModel(
            name='RequestSent',
        ),
    ]
