# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_lendituser_new_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendituser',
            name='small_pic_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
