# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-21 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20161121_2007'),
        ('website', '0007_lendituser_small_pic_url'),
    ]

    operations = [
    ]
