# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-21 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20161121_2044'),
        ('website', '0008_merge'),
    ]

    operations = [
    ]
