# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160813_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='status',
            field=models.CharField(choices=[('Lent', 'Lent'), ('Available', 'Available')], default='Available', max_length=10),
        ),
    ]
