# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160813_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='accepted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
