# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160813_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendituser',
            name='new_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
